version = 1
id_buy = "01"

default_fare = "super_sparpreis"
fallback_fares = ["sparpreis", "flexpreis", "cheapest_available"]
travel_class = "second"
continue_to_customer_data = true
booking_for = "self"
continue_to_payment_boundary = true
