version = 1
ID_PYM = "01"
method = "sepa"

[payment.sepa]
accountOwner = "fill-account-owner"
iban = "fill-iban"
birthdate = "1962-09-02"
streetNhouseNum = "fill-street-and-house-number"
additionalInfo = "fill-other-address-info"
zip = "fill-postcode"
city = "fill-city"
country = "Germany"
mandateAccepted = true
saveAsPreferred = false

[payment.card]
cardholderName = "fill-cardholder-name"
cardNumber = "fill-card-number"
expiryMonth = "fill-expiry-month"
expiryYear = "fill-expiry-year"
saveAsPreferred = false
