version = 1
id_pym = "01"
method = "sepa"

[payment.sepa]
account_owner = "fill-account-owner"
iban = "fill-iban"
birthdate = "1962-09-02"
street_number = "fill-street-and-house-number"
additional_info = "fill-other-address-info"
zip = "fill-postcode"
city = "fill-city"
country = "Germany"
mandate_accepted = true
save_as_preferred = false

[payment.card]
cardholder_name = "fill-cardholder-name"
card_number = "fill-card-number"
expiry_month = "fill-expiry-month"
expiry_year = "fill-expiry-year"
save_as_preferred = false
